### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-05-18/MEAN-sofiajhk#1]
Please push your latest assignments.

**Comment by dojo-json** [comment]
Any updates on this?

**Comment by sofiajhk** [comment]
Hi Jason! 

Sorry! I am out of town at the moment and don’t have my laptop with me but I’ll be back Sunday. Is it ok if I get everything updated and pushed by then??

**Comment by dojo-json** [comment]
I imagine you've returned at this point. Updates?
